{identifier:"abbreviation",
items: [
  {name:"AL - Alabama", label:"AL - Alabama",abbreviation:"AL"},
  {name:"AK - Alaska", label:"AK - Alaska",abbreviation:"AK"},
  {name:"AZ - Arizona", label:"AZ - Arizona",abbreviation:"AZ"},
  {name:"AR - Arkansas", label:"AR - Arkansas",abbreviation:"AR"},
  {name:"CA - California", label:"CA - California",abbreviation:"CA"},
  {name:"CO - Colorado", label:"CO - Colorado",abbreviation:"CO"},
  {name:"CT - Connecticut", label:"CT - Connecticut",abbreviation:"CT"},
  {name:"DE - Delaware", label:"DE - Delaware",abbreviation:"DE"},
  {name:"DC - District of Columbia", label:"DC - District of Columbia",abbreviation:"DC"},
  {name:"FL - Florida", label:"FL - Florida",abbreviation:"FL"},
  {name:"GA - Georgia", label:"GA - Georgia",abbreviation:"GA"},
  {name:"HI - Hawaii", label:"HI - Hawaii",abbreviation:"HI"},
  {name:"ID - Idaho", label:"ID - Idaho",abbreviation:"ID"},
  {name:"IL - Illinois", label:"IL - Illinois",abbreviation:"IL"},
  {name:"IN - Indiana", label:"IN - Indiana",abbreviation:"IN"},
  {name:"IA - Iowa", label:"IA - Iowa",abbreviation:"IA"},
  {name:"KS - Kansas", label:"KS - Kansas",abbreviation:"KS"},
  {name:"KY - Kentucky", label:"KY - Kentucky",abbreviation:"KY"},
  {name:"LA - Louisiana", label:"LA - Louisiana",abbreviation:"LA"},
  {name:"ME - Maine", label:"ME - Maine",abbreviation:"ME"},
  {name:"MD - Maryland", label:"MD - Maryland",abbreviation:"MD"},
  {name:"MA - Massachusetts", label:"MA - Massachusetts",abbreviation:"MA"},
  {name:"MI - Michigan", label:"MI - Michigan",abbreviation:"MI"},
  {name:"MN - Minnesota", label:"MN - Minnesota",abbreviation:"MN"},
  {name:"MS - Mississippi", label:"MS - Mississippi",abbreviation:"MS"},
  {name:"MO - Missouri", label:"MO - Missouri",abbreviation:"MO"},
  {name:"MT - Montana", label:"MT - Montana",abbreviation:"MT"},
  {name:"NE - Nebraska", label:"NE - Nebraska",abbreviation:"NE"},
  {name:"NV - Nevada", label:"NV - Nevada",abbreviation:"NV"},
  {name:"NH - New Hampshire", label:"NH - New Hampshire",abbreviation:"NH"},
  {name:"NJ - New Jersey", label:"NJ - New Jersey",abbreviation:"NJ"},
  {name:"NM - New Mexico", label:"NM - New Mexico",abbreviation:"NM"},
  {name:"NY - New York", label:"NY - New York",abbreviation:"NY"},
  {name:"NC - North Carolina", label:"NC - North Carolina",abbreviation:"NC"},
  {name:"ND - North Dakota", label:"ND - North Dakota",abbreviation:"ND"},
  {name:"OH - Ohio", label:"OH - Ohio",abbreviation:"OH"},
  {name:"OK - Oklahoma", label:"OK - Oklahoma",abbreviation:"OK"},
  {name:"OR - Oregon", label:"OR - Oregon",abbreviation:"OR"},
  {name:"PA - Pennsylvania", label:"PA - Pennsylvania",abbreviation:"PA"},
  {name:"PR - Puerto Rico", label:"PR - Puerto Rico",abbreviation:"PR"},
  {name:"RI - Rhode Island", label:"RI - Rhode Island",abbreviation:"RI"},
  {name:"SC - South Carolina", label:"SC - South Carolina",abbreviation:"SC"},
  {name:"SD - South Dakota", label:"SD - South Dakota",abbreviation:"SD"},
  {name:"TN - Tennessee", label:"TN - Tennessee",abbreviation:"TN"},
  {name:"TX - Texas", label:"TX - Texas",abbreviation:"TX"},
  {name:"UT - Utah", label:"UT - Utah",abbreviation:"UT"},
  {name:"VT - Vermont", label:"VT - Vermont",abbreviation:"VT"},
  {name:"VA - Virginia", label:"VVA - Virginia",abbreviation:"VA"},
  {name:"WA - Washington", label:"WA - Washington",abbreviation:"WA"},
  {name:"WV - West Virginia", label:"WV - West Virginia",abbreviation:"WV"},
  {name:"WI - Wisconsin", label:"WI - Wisconsin",abbreviation:"WI"},
  {name:"WY - Wyoming", label:"WY - Wyoming",abbreviation:"WY"},
  {name:"AB - Alberta", label:"AB - Alberta",abbreviation:"AB"},
  {name:"BC - British Columbia", label:"BC - British Columbia",abbreviation:"BC"},
  {name:"MB - Manitoba", label:"MB - Manitoba",abbreviation:"MB"},
  {name:"NB - New Brunswick", label:"NB - New Brunswick",abbreviation:"NB"},
  {name:"NL - Newfoundland and Labrador", label:"NL - Newfoundland and Labrador",abbreviation:"NL"},
  {name:"NS - Nova Scotia", label:"NS - Nova Scotia",abbreviation:"NS"},
  {name:"NT - Northwest Territories", label:"NT - Northwest Territories",abbreviation:"NT"},
  {name:"NU - Nunavut", label:"NU - Nunavut",abbreviation:"NU"},
  {name:"ON - Ontario", label:"ON - Ontario",abbreviation:"ON"},
  {name:"PE - Prince Edward Island", label:"PE - Prince Edward Island",abbreviation:"PE"},
  {name:"QC - Quebec", label:"QC - Quebec",abbreviation:"QC"},
  {name:"SK - Saskatchewan", label:"SK - Saskatchewan",abbreviation:"SK"},
  {name:"YT - Yukon Territory", label:"YT - Yukon Territory",abbreviation:"YT"}
]}
<%-- @version $Id: //application/service-UI/version/11.2/framework/Agent/src/web-apps/ServiceFramework/include/addresses/stateData.jsp#1 $$Change: 946917 $--%>
