//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.21 at 03:43:50 PM UTC 
//


package com.googleadwords.beans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import com.googleadwords.beans.CDATAAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://base.google.com/ns/1.0}id"/>
 *         &lt;element ref="{http://base.google.com/ns/1.0}title"/>
 *         &lt;element ref="{http://base.google.com/ns/1.0}description"/>
 *         &lt;element ref="{http://base.google.com/ns/1.0}link"/>
 *         &lt;element ref="{http://base.google.com/ns/1.0}image_link"/>
 *         &lt;element ref="{http://base.google.com/ns/1.0}condition"/>
 *         &lt;element ref="{http://base.google.com/ns/1.0}availability"/>
 *         &lt;element ref="{http://base.google.com/ns/1.0}price"/>
 *         &lt;element ref="{http://base.google.com/ns/1.0}shipping" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://base.google.com/ns/1.0}gtin"/>
 *         &lt;element ref="{http://base.google.com/ns/1.0}brand"/>
 *         &lt;element ref="{http://base.google.com/ns/1.0}google_product_category"/>
 *         &lt;element ref="{http://base.google.com/ns/1.0}product_type"/>
 *         &lt;element ref="{http://base.google.com/ns/1.0}additional_image_link"/>
 *         &lt;element ref="{http://base.google.com/ns/1.0}gender"/>
 *         &lt;element ref="{http://base.google.com/ns/1.0}age_group"/>
 *         &lt;element ref="{http://base.google.com/ns/1.0}color"/>
 *         &lt;element ref="{http://base.google.com/ns/1.0}size"/>
 *         &lt;element ref="{http://base.google.com/ns/1.0}item_group_id"/>
 *         &lt;element ref="{http://base.google.com/ns/1.0}sale_price"/>
 *         &lt;element ref="{http://base.google.com/ns/1.0}sale_price_effective_date"/>
 *         &lt;element ref="{http://base.google.com/ns/1.0}adwords_labels"/>
 *         &lt;element ref="{http://base.google.com/ns/1.0}pickup_link_template"/>
 *         &lt;element ref="{http://base.google.com/ns/1.0}mobile_pickup_link_template"/>
 *         &lt;element ref="{http://base.google.com/ns/1.0}custom_label_0"/>
 *         &lt;element ref="{http://base.google.com/ns/1.0}custom_label_1"/>
 *         &lt;element ref="{http://base.google.com/ns/1.0}custom_label_2"/>
 *         &lt;element ref="{http://base.google.com/ns/1.0}custom_label_3"/>
 *         &lt;element ref="{http://base.google.com/ns/1.0}custom_label_4"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "title",
    "description",
    "link",
    "imageLink",
    "condition",
    "availability",
    "price",
    "shipping",
    "gtin",
    "brand",
    "googleProductCategory",
    "productType",
    "additionalImageLink",
    "gender",
    "ageGroup",
    "color",
    "size",
    "itemGroupId",
    "salePrice",
    "salePriceEffectiveDate",
    "adwordsLabels",
	"pickupLinkTemplate",
	"mobilePickupLinkTemplate",
    "customLabel0",
    "customLabel1",
    "customLabel2",
    "customLabel3",
    "customLabel4"
})
@XmlRootElement(name = "item")
public class Item {

    @XmlElement(namespace = "http://base.google.com/ns/1.0", required = true)
    protected String id;
    @XmlElement(namespace = "http://base.google.com/ns/1.0", required = true)
    @XmlJavaTypeAdapter(value=CDATAAdapter.class)
    protected String title;
    @XmlElement(namespace = "http://base.google.com/ns/1.0", required = true)
    @XmlJavaTypeAdapter(value=CDATAAdapter.class)
    protected String description;
    @XmlElement(namespace = "http://base.google.com/ns/1.0", required = true)
    @XmlSchemaType(name = "anyURI")
    @XmlJavaTypeAdapter(value=CDATAAdapter.class)
    protected String link;
    @XmlElement(name = "image_link", namespace = "http://base.google.com/ns/1.0", required = true)
    @XmlSchemaType(name = "anyURI")
    @XmlJavaTypeAdapter(value=CDATAAdapter.class)
    protected String imageLink;
    @XmlElement(namespace = "http://base.google.com/ns/1.0", required = true)
    protected String condition;
    @XmlElement(namespace = "http://base.google.com/ns/1.0", required = true)
    protected String availability;
    @XmlElement(namespace = "http://base.google.com/ns/1.0", required = true)
    protected String price;
    @XmlElement(namespace = "http://base.google.com/ns/1.0")
    protected List<Shipping> shipping;
    @XmlElement(namespace = "http://base.google.com/ns/1.0", required = true)
    protected String gtin;
    @XmlElement(namespace = "http://base.google.com/ns/1.0", required = true)
    @XmlJavaTypeAdapter(value=CDATAAdapter.class)
    protected String brand;
    @XmlElement(name = "google_product_category", namespace = "http://base.google.com/ns/1.0", required = true)
    @XmlJavaTypeAdapter(value=CDATAAdapter.class)
    protected String googleProductCategory;
    @XmlElement(name = "product_type", namespace = "http://base.google.com/ns/1.0", required = true)
    @XmlJavaTypeAdapter(value=CDATAAdapter.class)
    protected String productType;
    @XmlElement(name = "additional_image_link", namespace = "http://base.google.com/ns/1.0", required = true)
    @XmlSchemaType(name = "anyURI")
    @XmlJavaTypeAdapter(value=CDATAAdapter.class)
    protected String additionalImageLink;
    @XmlElement(namespace = "http://base.google.com/ns/1.0", required = true)
    protected String gender;
    @XmlElement(name = "age_group", namespace = "http://base.google.com/ns/1.0", required = true)
    protected String ageGroup;
    @XmlElement(namespace = "http://base.google.com/ns/1.0", required = true)
    protected String color;
    @XmlElement(namespace = "http://base.google.com/ns/1.0", required = true)
    protected String size;
    @XmlElement(name = "item_group_id", namespace = "http://base.google.com/ns/1.0", required = true)
    protected String itemGroupId;
    @XmlElement(name = "sale_price", namespace = "http://base.google.com/ns/1.0", required = true)
    protected String salePrice;
    @XmlElement(name = "sale_price_effective_date", namespace = "http://base.google.com/ns/1.0", required = true)
    protected String salePriceEffectiveDate;
	@XmlElement(name = "adwords_labels", namespace = "http://base.google.com/ns/1.0", required = true)
    @XmlJavaTypeAdapter(value=CDATAAdapter.class)
    protected String adwordsLabels;
    @XmlElement(name = "pickup_link_template", namespace = "http://base.google.com/ns/1.0", required = true)
    @XmlJavaTypeAdapter(value=CDATAAdapter.class)
    protected String pickupLinkTemplate;
	@XmlElement(name = "mobile_pickup_link_template", namespace = "http://base.google.com/ns/1.0", required = true)
    @XmlJavaTypeAdapter(value=CDATAAdapter.class)
    protected String mobilePickupLinkTemplate;
    @XmlElement(name = "custom_label_0", namespace = "http://base.google.com/ns/1.0", required = true)
    @XmlJavaTypeAdapter(value=CDATAAdapter.class)
    protected String customLabel0;
    @XmlElement(name = "custom_label_1", namespace = "http://base.google.com/ns/1.0", required = true)
    @XmlJavaTypeAdapter(value=CDATAAdapter.class)
    protected String customLabel1;
    @XmlElement(name = "custom_label_2", namespace = "http://base.google.com/ns/1.0", required = true)
    @XmlJavaTypeAdapter(value=CDATAAdapter.class)
    protected String customLabel2;
    @XmlElement(name = "custom_label_3", namespace = "http://base.google.com/ns/1.0", required = true)
    @XmlJavaTypeAdapter(value=CDATAAdapter.class)
    protected String customLabel3;
    @XmlElement(name = "custom_label_4", namespace = "http://base.google.com/ns/1.0", required = true)
    @XmlJavaTypeAdapter(value=CDATAAdapter.class)
    protected String customLabel4;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLink(String value) {
        this.link = value;
    }

    /**
     * Gets the value of the imageLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageLink() {
        return imageLink;
    }

    /**
     * Sets the value of the imageLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageLink(String value) {
        this.imageLink = value;
    }

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCondition(String value) {
        this.condition = value;
    }

    /**
     * Gets the value of the availability property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvailability() {
        return availability;
    }

    /**
     * Sets the value of the availability property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvailability(String value) {
        this.availability = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrice(String value) {
        this.price = value;
    }

    /**
     * Gets the value of the shipping property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the shipping property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getShipping().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Shipping }
     * 
     * 
     */
    public List<Shipping> getShipping() {
        if (shipping == null) {
            shipping = new ArrayList<Shipping>();
        }
        return this.shipping;
    }

    /**
     * Gets the value of the gtin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGtin() {
        return gtin;
    }

    /**
     * Sets the value of the gtin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGtin(String value) {
        this.gtin = value;
    }

    /**
     * Gets the value of the brand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrand() {
        return brand;
    }

    /**
     * Sets the value of the brand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrand(String value) {
        this.brand = value;
    }

    /**
     * Gets the value of the googleProductCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGoogleProductCategory() {
        return googleProductCategory;
    }

    /**
     * Sets the value of the googleProductCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGoogleProductCategory(String value) {
        this.googleProductCategory = value;
    }

    /**
     * Gets the value of the productType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductType() {
        return productType;
    }

    /**
     * Sets the value of the productType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductType(String value) {
        this.productType = value;
    }

    /**
     * Gets the value of the additionalImageLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalImageLink() {
        return additionalImageLink;
    }

    /**
     * Sets the value of the additionalImageLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalImageLink(String value) {
        this.additionalImageLink = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the ageGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgeGroup() {
        return ageGroup;
    }

    /**
     * Sets the value of the ageGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgeGroup(String value) {
        this.ageGroup = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSize(String value) {
        this.size = value;
    }

    /**
     * Gets the value of the itemGroupId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemGroupId() {
        return itemGroupId;
    }

    /**
     * Sets the value of the itemGroupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemGroupId(String value) {
        this.itemGroupId = value;
    }

    /**
     * Gets the value of the salePrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalePrice() {
        return salePrice;
    }

    /**
     * Sets the value of the salePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalePrice(String value) {
        this.salePrice = value;
    }

    /**
     * Gets the value of the salePriceEffectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalePriceEffectiveDate() {
        return salePriceEffectiveDate;
    }

    /**
     * Sets the value of the salePriceEffectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalePriceEffectiveDate(String value) {
        this.salePriceEffectiveDate = value;
    }

    /**
     * Gets the value of the adwordsLabels property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdwordsLabels() {
        return adwordsLabels;
    }

    /**
     * Sets the value of the adwordsLabels property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdwordsLabels(String value) {
        this.adwordsLabels = value;
    }
	
	/**
     * Gets the value of the pickupLinkTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPickupLinkTemplate() {
        return pickupLinkTemplate;
    }

    /**
     * Sets the value of the pickupLinkTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPickupLinkTemplate(String value) {
        this.pickupLinkTemplate = value;
    }
	
		/**
     * Gets the value of the mobilePickupLinkTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobilePickupLinkTemplate() {
        return mobilePickupLinkTemplate;
    }

    /**
     * Sets the value of the mobilePickupLinkTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobilePickupLinkTemplate(String value) {
        this.mobilePickupLinkTemplate = value;
    }

    /**
     * Gets the value of the customLabel0 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomLabel0() {
        return customLabel0;
    }

    /**
     * Sets the value of the customLabel0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomLabel0(String value) {
        this.customLabel0 = value;
    }

    /**
     * Gets the value of the customLabel1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomLabel1() {
        return customLabel1;
    }

    /**
     * Sets the value of the customLabel1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomLabel1(String value) {
        this.customLabel1 = value;
    }

    /**
     * Gets the value of the customLabel2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomLabel2() {
        return customLabel2;
    }

    /**
     * Sets the value of the customLabel2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomLabel2(String value) {
        this.customLabel2 = value;
    }

    /**
     * Gets the value of the customLabel3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomLabel3() {
        return customLabel3;
    }

    /**
     * Sets the value of the customLabel3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomLabel3(String value) {
        this.customLabel3 = value;
    }

    /**
     * Gets the value of the customLabel4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomLabel4() {
        return customLabel4;
    }

    /**
     * Sets the value of the customLabel4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomLabel4(String value) {
        this.customLabel4 = value;
    }

}
