//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.21 at 03:43:50 PM UTC 
//


package com.googleadwords.beans;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.googleadwords.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GoogleProductCategory_QNAME = new QName("http://base.google.com/ns/1.0", "google_product_category");
    private final static QName _AdditionalImageLink_QNAME = new QName("http://base.google.com/ns/1.0", "additional_image_link");
    private final static QName _ItemGroupId_QNAME = new QName("http://base.google.com/ns/1.0", "item_group_id");
    private final static QName _Color_QNAME = new QName("http://base.google.com/ns/1.0", "color");
    private final static QName _Price_QNAME = new QName("http://base.google.com/ns/1.0", "price");
    private final static QName _AgeGroup_QNAME = new QName("http://base.google.com/ns/1.0", "age_group");
    private final static QName _Brand_QNAME = new QName("http://base.google.com/ns/1.0", "brand");
    private final static QName _Gtin_QNAME = new QName("http://base.google.com/ns/1.0", "gtin");
    private final static QName _Condition_QNAME = new QName("http://base.google.com/ns/1.0", "condition");
    private final static QName _SalePrice_QNAME = new QName("http://base.google.com/ns/1.0", "sale_price");
    private final static QName _SalePriceEffectiveDate_QNAME = new QName("http://base.google.com/ns/1.0", "sale_price_effective_date");
    private final static QName _Size_QNAME = new QName("http://base.google.com/ns/1.0", "size");
    private final static QName _ImageLink_QNAME = new QName("http://base.google.com/ns/1.0", "image_link");
    private final static QName _ProductType_QNAME = new QName("http://base.google.com/ns/1.0", "product_type");
    private final static QName _Description_QNAME = new QName("http://base.google.com/ns/1.0", "description");
    private final static QName _Title_QNAME = new QName("http://base.google.com/ns/1.0", "title");
    private final static QName _Id_QNAME = new QName("http://base.google.com/ns/1.0", "id");
    private final static QName _CustomLabel0_QNAME = new QName("http://base.google.com/ns/1.0", "custom_label_0");
    private final static QName _CustomLabel1_QNAME = new QName("http://base.google.com/ns/1.0", "custom_label_1");
    private final static QName _Availability_QNAME = new QName("http://base.google.com/ns/1.0", "availability");
    private final static QName _CustomLabel2_QNAME = new QName("http://base.google.com/ns/1.0", "custom_label_2");
    private final static QName _CustomLabel3_QNAME = new QName("http://base.google.com/ns/1.0", "custom_label_3");
    private final static QName _CustomLabel4_QNAME = new QName("http://base.google.com/ns/1.0", "custom_label_4");
    private final static QName _Gender_QNAME = new QName("http://base.google.com/ns/1.0", "gender");
    private final static QName _Link_QNAME = new QName("http://base.google.com/ns/1.0", "link");
    private final static QName _Mpn_QNAME = new QName("http://base.google.com/ns/1.0", "mpn");
    private final static QName _AdwordsLabels_QNAME = new QName("http://base.google.com/ns/1.0", "adwords_labels");
	private final static QName _PickupLinkTemplate_QNAME = new QName("http://base.google.com/ns/1.0", "pickup_link_template");
	private final static QName _MobilePickupLinkTemplate_QNAME = new QName("http://base.google.com/ns/1.0", "mobile_pickup_link_template");
	

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.googleadwords.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link Shipping }
     * 
     */
    public Shipping createShipping() {
        return new Shipping();
    }

    /**
     * Create an instance of {@link Rss }
     * 
     */
    public Rss createRss() {
        return new Rss();
    }

    /**
     * Create an instance of {@link Channel }
     * 
     */
    public Channel createChannel() {
        return new Channel();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://base.google.com/ns/1.0", name = "google_product_category")
    public JAXBElement<String> createGoogleProductCategory(String value) {
        return new JAXBElement<String>(_GoogleProductCategory_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://base.google.com/ns/1.0", name = "additional_image_link")
    public JAXBElement<String> createAdditionalImageLink(String value) {
        return new JAXBElement<String>(_AdditionalImageLink_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://base.google.com/ns/1.0", name = "item_group_id")
    public JAXBElement<String> createItemGroupId(String value) {
        return new JAXBElement<String>(_ItemGroupId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://base.google.com/ns/1.0", name = "color")
    public JAXBElement<String> createColor(String value) {
        return new JAXBElement<String>(_Color_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://base.google.com/ns/1.0", name = "price")
    public JAXBElement<String> createPrice(String value) {
        return new JAXBElement<String>(_Price_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://base.google.com/ns/1.0", name = "age_group")
    public JAXBElement<String> createAgeGroup(String value) {
        return new JAXBElement<String>(_AgeGroup_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://base.google.com/ns/1.0", name = "brand")
    public JAXBElement<String> createBrand(String value) {
        return new JAXBElement<String>(_Brand_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://base.google.com/ns/1.0", name = "gtin")
    public JAXBElement<String> createGtin(String value) {
        return new JAXBElement<String>(_Gtin_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://base.google.com/ns/1.0", name = "condition")
    public JAXBElement<String> createCondition(String value) {
        return new JAXBElement<String>(_Condition_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://base.google.com/ns/1.0", name = "sale_price")
    public JAXBElement<String> createSalePrice(String value) {
        return new JAXBElement<String>(_SalePrice_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://base.google.com/ns/1.0", name = "sale_price_effective_date")
    public JAXBElement<String> createSalePriceEffectiveDate(String value) {
        return new JAXBElement<String>(_SalePriceEffectiveDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://base.google.com/ns/1.0", name = "size")
    public JAXBElement<String> createSize(String value) {
        return new JAXBElement<String>(_Size_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://base.google.com/ns/1.0", name = "image_link")
    public JAXBElement<String> createImageLink(String value) {
        return new JAXBElement<String>(_ImageLink_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://base.google.com/ns/1.0", name = "product_type")
    public JAXBElement<String> createProductType(String value) {
        return new JAXBElement<String>(_ProductType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://base.google.com/ns/1.0", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://base.google.com/ns/1.0", name = "title")
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://base.google.com/ns/1.0", name = "id")
    public JAXBElement<String> createId(String value) {
        return new JAXBElement<String>(_Id_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://base.google.com/ns/1.0", name = "custom_label_0")
    public JAXBElement<String> createCustomLabel0(String value) {
        return new JAXBElement<String>(_CustomLabel0_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://base.google.com/ns/1.0", name = "custom_label_1")
    public JAXBElement<String> createCustomLabel1(String value) {
        return new JAXBElement<String>(_CustomLabel1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://base.google.com/ns/1.0", name = "availability")
    public JAXBElement<String> createAvailability(String value) {
        return new JAXBElement<String>(_Availability_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://base.google.com/ns/1.0", name = "custom_label_2")
    public JAXBElement<String> createCustomLabel2(String value) {
        return new JAXBElement<String>(_CustomLabel2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://base.google.com/ns/1.0", name = "custom_label_3")
    public JAXBElement<String> createCustomLabel3(String value) {
        return new JAXBElement<String>(_CustomLabel3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://base.google.com/ns/1.0", name = "custom_label_4")
    public JAXBElement<String> createCustomLabel4(String value) {
        return new JAXBElement<String>(_CustomLabel4_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://base.google.com/ns/1.0", name = "gender")
    public JAXBElement<String> createGender(String value) {
        return new JAXBElement<String>(_Gender_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://base.google.com/ns/1.0", name = "link")
    public JAXBElement<String> createLink(String value) {
        return new JAXBElement<String>(_Link_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://base.google.com/ns/1.0", name = "mpn")
    public JAXBElement<String> createMpn(String value) {
        return new JAXBElement<String>(_Mpn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://base.google.com/ns/1.0", name = "adwords_labels")
    public JAXBElement<String> createAdwordsLabels(String value) {
        return new JAXBElement<String>(_AdwordsLabels_QNAME, String.class, null, value);
    }
	
	/**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://base.google.com/ns/1.0", name = "pickup_link_template")
    public JAXBElement<String> createPickupLinkTemplate(String value) {
        return new JAXBElement<String>(_PickupLinkTemplate_QNAME, String.class, null, value);
    }
	
	/**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://base.google.com/ns/1.0", name = "mobile_pickup_link_template")
    public JAXBElement<String> createMobilePickupLinkTemplate(String value) {
        return new JAXBElement<String>(_MobilePickupLinkTemplate_QNAME, String.class, null, value);
    }

}
