//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.28 at 03:52:49 PM EDT 
//


package oms.commerce.salesaudit.schema.sale;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the oms.commerce.salesaudit.schema.sale package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SalesOrderLoyaltyIdentifier_QNAME = new QName("", "loyalty_identifier");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: oms.commerce.salesaudit.schema.sale
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Sales }
     * 
     */
    public Sales createSales() {
        return new Sales();
    }

    /**
     * Create an instance of {@link Sales.Summary.Auxiliaries }
     * 
     */
    public Sales.Summary.Auxiliaries createSalesSummaryAuxiliaries() {
        return new Sales.Summary.Auxiliaries();
    }

    /**
     * Create an instance of {@link SalesOrder.Appeasements }
     * 
     */
    public SalesOrder.Appeasements createSalesOrderAppeasements() {
        return new SalesOrder.Appeasements();
    }

    /**
     * Create an instance of {@link SalesOrder.Cartons }
     * 
     */
    public SalesOrder.Cartons createSalesOrderCartons() {
        return new SalesOrder.Cartons();
    }

    /**
     * Create an instance of {@link Period }
     * 
     */
    public Period createPeriod() {
        return new Period();
    }

    /**
     * Create an instance of {@link ContactType }
     * 
     */
    public ContactType createContactType() {
        return new ContactType();
    }

    /**
     * Create an instance of {@link SalesOrder.ShippingAmount }
     * 
     */
    public SalesOrder.ShippingAmount createSalesOrderShippingAmount() {
        return new SalesOrder.ShippingAmount();
    }

    /**
     * Create an instance of {@link SalesOrder.Lines.Shipped.Serials }
     * 
     */
    public SalesOrder.Lines.Shipped.Serials createSalesOrderLinesShippedSerials() {
        return new SalesOrder.Lines.Shipped.Serials();
    }

    /**
     * Create an instance of {@link SalesOrder.Auxiliaries.Auxiliary }
     * 
     */
    public SalesOrder.Auxiliaries.Auxiliary createSalesOrderAuxiliariesAuxiliary() {
        return new SalesOrder.Auxiliaries.Auxiliary();
    }

    /**
     * Create an instance of {@link TaxAmount }
     * 
     */
    public TaxAmount createTaxAmount() {
        return new TaxAmount();
    }

    /**
     * Create an instance of {@link AddressLineType }
     * 
     */
    public AddressLineType createAddressLineType() {
        return new AddressLineType();
    }

    /**
     * Create an instance of {@link CustomerType }
     * 
     */
    public CustomerType createCustomerType() {
        return new CustomerType();
    }

    /**
     * Create an instance of {@link SalesOrder.Lines }
     * 
     */
    public SalesOrder.Lines createSalesOrderLines() {
        return new SalesOrder.Lines();
    }

    /**
     * Create an instance of {@link OrderPayment }
     * 
     */
    public OrderPayment createOrderPayment() {
        return new OrderPayment();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link Sales.Summary.Payments.Payment }
     * 
     */
    public Sales.Summary.Payments.Payment createSalesSummaryPaymentsPayment() {
        return new Sales.Summary.Payments.Payment();
    }

    /**
     * Create an instance of {@link SalesOrder }
     * 
     */
    public SalesOrder createSalesOrder() {
        return new SalesOrder();
    }

    /**
     * Create an instance of {@link Sales.Orders }
     * 
     */
    public Sales.Orders createSalesOrders() {
        return new Sales.Orders();
    }

    /**
     * Create an instance of {@link SalesOrder.Lines.Returned.Sku }
     * 
     */
    public SalesOrder.Lines.Returned.Sku createSalesOrderLinesReturnedSku() {
        return new SalesOrder.Lines.Returned.Sku();
    }

    /**
     * Create an instance of {@link OrderPayment.Auxiliaries.Auxiliary }
     * 
     */
    public OrderPayment.Auxiliaries.Auxiliary createOrderPaymentAuxiliariesAuxiliary() {
        return new OrderPayment.Auxiliaries.Auxiliary();
    }

    /**
     * Create an instance of {@link SalesOrder.Lines.Returned }
     * 
     */
    public SalesOrder.Lines.Returned createSalesOrderLinesReturned() {
        return new SalesOrder.Lines.Returned();
    }

    /**
     * Create an instance of {@link Sales.Summary.Auxiliaries.Auxiliary }
     * 
     */
    public Sales.Summary.Auxiliaries.Auxiliary createSalesSummaryAuxiliariesAuxiliary() {
        return new Sales.Summary.Auxiliaries.Auxiliary();
    }

    /**
     * Create an instance of {@link LineDiscountType }
     * 
     */
    public LineDiscountType createLineDiscountType() {
        return new LineDiscountType();
    }

    /**
     * Create an instance of {@link OrderPayment.Auxiliaries }
     * 
     */
    public OrderPayment.Auxiliaries createOrderPaymentAuxiliaries() {
        return new OrderPayment.Auxiliaries();
    }

    /**
     * Create an instance of {@link SalesOrder.Lines.Returned.RestockingFee }
     * 
     */
    public SalesOrder.Lines.Returned.RestockingFee createSalesOrderLinesReturnedRestockingFee() {
        return new SalesOrder.Lines.Returned.RestockingFee();
    }

    /**
     * Create an instance of {@link SalesOrder.Lines.Returned.Discounts }
     * 
     */
    public SalesOrder.Lines.Returned.Discounts createSalesOrderLinesReturnedDiscounts() {
        return new SalesOrder.Lines.Returned.Discounts();
    }

    /**
     * Create an instance of {@link SalesOrder.Summary.Auxiliaries }
     * 
     */
    public SalesOrder.Summary.Auxiliaries createSalesOrderSummaryAuxiliaries() {
        return new SalesOrder.Summary.Auxiliaries();
    }

    /**
     * Create an instance of {@link SalesOrder.Lines.Returned.Auxiliaries.Auxiliary }
     * 
     */
    public SalesOrder.Lines.Returned.Auxiliaries.Auxiliary createSalesOrderLinesReturnedAuxiliariesAuxiliary() {
        return new SalesOrder.Lines.Returned.Auxiliaries.Auxiliary();
    }

    /**
     * Create an instance of {@link Sales.Summary }
     * 
     */
    public Sales.Summary createSalesSummary() {
        return new Sales.Summary();
    }

    /**
     * Create an instance of {@link OrderAppeasementType }
     * 
     */
    public OrderAppeasementType createOrderAppeasementType() {
        return new OrderAppeasementType();
    }

    /**
     * Create an instance of {@link SalesOrder.Cartons.Carton }
     * 
     */
    public SalesOrder.Cartons.Carton createSalesOrderCartonsCarton() {
        return new SalesOrder.Cartons.Carton();
    }

    /**
     * Create an instance of {@link SalesOrder.Lines.Returned.Auxiliaries }
     * 
     */
    public SalesOrder.Lines.Returned.Auxiliaries createSalesOrderLinesReturnedAuxiliaries() {
        return new SalesOrder.Lines.Returned.Auxiliaries();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link SalesOrder.Summary }
     * 
     */
    public SalesOrder.Summary createSalesOrderSummary() {
        return new SalesOrder.Summary();
    }

    /**
     * Create an instance of {@link SalesOrder.Lines.Shipped.Tracking.Carton }
     * 
     */
    public SalesOrder.Lines.Shipped.Tracking.Carton createSalesOrderLinesShippedTrackingCarton() {
        return new SalesOrder.Lines.Shipped.Tracking.Carton();
    }

    /**
     * Create an instance of {@link SalesOrder.Payments }
     * 
     */
    public SalesOrder.Payments createSalesOrderPayments() {
        return new SalesOrder.Payments();
    }

    /**
     * Create an instance of {@link SalesOrder.Lines.Shipped.Tracking }
     * 
     */
    public SalesOrder.Lines.Shipped.Tracking createSalesOrderLinesShippedTracking() {
        return new SalesOrder.Lines.Shipped.Tracking();
    }

    /**
     * Create an instance of {@link SalesOrder.Auxiliaries }
     * 
     */
    public SalesOrder.Auxiliaries createSalesOrderAuxiliaries() {
        return new SalesOrder.Auxiliaries();
    }

    /**
     * Create an instance of {@link Sales.Summary.Payments }
     * 
     */
    public Sales.Summary.Payments createSalesSummaryPayments() {
        return new Sales.Summary.Payments();
    }

    /**
     * Create an instance of {@link SalesOrder.Summary.Auxiliaries.Auxiliary }
     * 
     */
    public SalesOrder.Summary.Auxiliaries.Auxiliary createSalesOrderSummaryAuxiliariesAuxiliary() {
        return new SalesOrder.Summary.Auxiliaries.Auxiliary();
    }

    /**
     * Create an instance of {@link SalesOrder.Lines.Shipped }
     * 
     */
    public SalesOrder.Lines.Shipped createSalesOrderLinesShipped() {
        return new SalesOrder.Lines.Shipped();
    }

    /**
     * Create an instance of {@link SalesOrder.Lines.Shipped.Tracking.Carton.Serials }
     * 
     */
    public SalesOrder.Lines.Shipped.Tracking.Carton.Serials createSalesOrderLinesShippedTrackingCartonSerials() {
        return new SalesOrder.Lines.Shipped.Tracking.Carton.Serials();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "loyalty_identifier", scope = SalesOrder.class)
    public JAXBElement<String> createSalesOrderLoyaltyIdentifier(String value) {
        return new JAXBElement<String>(_SalesOrderLoyaltyIdentifier_QNAME, String.class, SalesOrder.class, value);
    }

}
