//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.28 at 03:52:49 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://speedorder.speedfc.com/xml/types")
package oms.commerce.salesaudit.schema.sale;
