//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.28 at 03:52:49 PM EDT 
//


package oms.commerce.salesaudit.schema.sale;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://speedorder.speedfc.com/xml/types}ReportHeader"/>
 *         &lt;element name="orders" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="order" type="{http://speedorder.speedfc.com/xml/sales}SalesOrder" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="summary" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="transactions_total" type="{http://speedorder.speedfc.com/xml/types}numeric19s2"/>
 *                   &lt;element name="transactions_taxable_total" type="{http://speedorder.speedfc.com/xml/types}numeric19s2" minOccurs="0"/>
 *                   &lt;element name="transactions_tax_total" type="{http://speedorder.speedfc.com/xml/types}numeric19s2"/>
 *                   &lt;element name="transactions_count" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="transaction_lines_count" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="payments_total" type="{http://speedorder.speedfc.com/xml/types}numeric19s2"/>
 *                   &lt;element name="payments_count" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="discounts_total" type="{http://speedorder.speedfc.com/xml/types}numeric19s2"/>
 *                   &lt;element name="discounts_count" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="giftcard_sold_total" type="{http://speedorder.speedfc.com/xml/types}numeric19s2"/>
 *                   &lt;element name="giftcard_sold_count" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="payments" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="payment" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;all>
 *                                       &lt;element name="credit_total" type="{http://speedorder.speedfc.com/xml/types}numeric19s2"/>
 *                                       &lt;element name="credit_count" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                                       &lt;element name="debit_total" type="{http://speedorder.speedfc.com/xml/types}numeric19s2"/>
 *                                       &lt;element name="debit_count" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                                     &lt;/all>
 *                                     &lt;attribute name="type" use="required" type="{http://speedorder.speedfc.com/xml/types}varchar10" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="auxiliaries" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice>
 *                             &lt;element name="auxiliary" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="1.2" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sequence",
    "generated",
    "reportDate",
    "reportPeriod",
    "orders",
    "summary"
})
@XmlRootElement(name = "sales", namespace = "http://speedorder.speedfc.com/xml/sales")
public class Sales {

    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger sequence;
    @XmlElement(required = true)
    protected String generated;
    @XmlElement(name = "report_date")
    protected String reportDate;
    @XmlElement(name = "report_period")
    protected Period reportPeriod;
    protected Sales.Orders orders;
    protected Sales.Summary summary;
    @XmlAttribute(required = true)
    protected String version;

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSequence(BigInteger value) {
        this.sequence = value;
    }

    /**
     * Gets the value of the generated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenerated() {
        return generated;
    }

    /**
     * Sets the value of the generated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenerated(String value) {
        this.generated = value;
    }

    /**
     * Gets the value of the reportDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportDate() {
        return reportDate;
    }

    /**
     * Sets the value of the reportDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportDate(String value) {
        this.reportDate = value;
    }

    /**
     * Gets the value of the reportPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link Period }
     *     
     */
    public Period getReportPeriod() {
        return reportPeriod;
    }

    /**
     * Sets the value of the reportPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Period }
     *     
     */
    public void setReportPeriod(Period value) {
        this.reportPeriod = value;
    }

    /**
     * Gets the value of the orders property.
     * 
     * @return
     *     possible object is
     *     {@link Sales.Orders }
     *     
     */
    public Sales.Orders getOrders() {
        return orders;
    }

    /**
     * Sets the value of the orders property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sales.Orders }
     *     
     */
    public void setOrders(Sales.Orders value) {
        this.orders = value;
    }

    /**
     * Gets the value of the summary property.
     * 
     * @return
     *     possible object is
     *     {@link Sales.Summary }
     *     
     */
    public Sales.Summary getSummary() {
        return summary;
    }

    /**
     * Sets the value of the summary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sales.Summary }
     *     
     */
    public void setSummary(Sales.Summary value) {
        this.summary = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.2";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="order" type="{http://speedorder.speedfc.com/xml/sales}SalesOrder" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "order"
    })
    public static class Orders {

        protected List<SalesOrder> order;

        /**
         * Gets the value of the order property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the order property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOrder().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SalesOrder }
         * 
         * 
         */
        public List<SalesOrder> getOrder() {
            if (order == null) {
                order = new ArrayList<SalesOrder>();
            }
            return this.order;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="transactions_total" type="{http://speedorder.speedfc.com/xml/types}numeric19s2"/>
     *         &lt;element name="transactions_taxable_total" type="{http://speedorder.speedfc.com/xml/types}numeric19s2" minOccurs="0"/>
     *         &lt;element name="transactions_tax_total" type="{http://speedorder.speedfc.com/xml/types}numeric19s2"/>
     *         &lt;element name="transactions_count" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="transaction_lines_count" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="payments_total" type="{http://speedorder.speedfc.com/xml/types}numeric19s2"/>
     *         &lt;element name="payments_count" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="discounts_total" type="{http://speedorder.speedfc.com/xml/types}numeric19s2"/>
     *         &lt;element name="discounts_count" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="giftcard_sold_total" type="{http://speedorder.speedfc.com/xml/types}numeric19s2"/>
     *         &lt;element name="giftcard_sold_count" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="payments" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="payment" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;all>
     *                             &lt;element name="credit_total" type="{http://speedorder.speedfc.com/xml/types}numeric19s2"/>
     *                             &lt;element name="credit_count" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                             &lt;element name="debit_total" type="{http://speedorder.speedfc.com/xml/types}numeric19s2"/>
     *                             &lt;element name="debit_count" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                           &lt;/all>
     *                           &lt;attribute name="type" use="required" type="{http://speedorder.speedfc.com/xml/types}varchar10" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="auxiliaries" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;element name="auxiliary" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "transactionsTotal",
        "transactionsTaxableTotal",
        "transactionsTaxTotal",
        "transactionsCount",
        "transactionLinesCount",
        "paymentsTotal",
        "paymentsCount",
        "discountsTotal",
        "discountsCount",
        "giftcardSoldTotal",
        "giftcardSoldCount",
        "payments",
        "auxiliaries"
    })
    public static class Summary {

        @XmlElement(name = "transactions_total", required = true)
        protected BigDecimal transactionsTotal;
        @XmlElement(name = "transactions_taxable_total")
        protected BigDecimal transactionsTaxableTotal;
        @XmlElement(name = "transactions_tax_total", required = true)
        protected BigDecimal transactionsTaxTotal;
        @XmlElement(name = "transactions_count", required = true)
        protected BigInteger transactionsCount;
        @XmlElement(name = "transaction_lines_count", required = true)
        protected BigInteger transactionLinesCount;
        @XmlElement(name = "payments_total", required = true)
        protected BigDecimal paymentsTotal;
        @XmlElement(name = "payments_count", required = true)
        protected BigInteger paymentsCount;
        @XmlElement(name = "discounts_total", required = true)
        protected BigDecimal discountsTotal;
        @XmlElement(name = "discounts_count", required = true)
        protected BigInteger discountsCount;
        @XmlElement(name = "giftcard_sold_total", required = true)
        protected BigDecimal giftcardSoldTotal;
        @XmlElement(name = "giftcard_sold_count", required = true)
        protected BigInteger giftcardSoldCount;
        protected Sales.Summary.Payments payments;
        protected Sales.Summary.Auxiliaries auxiliaries;

        /**
         * Gets the value of the transactionsTotal property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTransactionsTotal() {
            return transactionsTotal;
        }

        /**
         * Sets the value of the transactionsTotal property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setTransactionsTotal(BigDecimal value) {
            this.transactionsTotal = value;
        }

        /**
         * Gets the value of the transactionsTaxableTotal property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTransactionsTaxableTotal() {
            return transactionsTaxableTotal;
        }

        /**
         * Sets the value of the transactionsTaxableTotal property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setTransactionsTaxableTotal(BigDecimal value) {
            this.transactionsTaxableTotal = value;
        }

        /**
         * Gets the value of the transactionsTaxTotal property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTransactionsTaxTotal() {
            return transactionsTaxTotal;
        }

        /**
         * Sets the value of the transactionsTaxTotal property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setTransactionsTaxTotal(BigDecimal value) {
            this.transactionsTaxTotal = value;
        }

        /**
         * Gets the value of the transactionsCount property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTransactionsCount() {
            return transactionsCount;
        }

        /**
         * Sets the value of the transactionsCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTransactionsCount(BigInteger value) {
            this.transactionsCount = value;
        }

        /**
         * Gets the value of the transactionLinesCount property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTransactionLinesCount() {
            return transactionLinesCount;
        }

        /**
         * Sets the value of the transactionLinesCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTransactionLinesCount(BigInteger value) {
            this.transactionLinesCount = value;
        }

        /**
         * Gets the value of the paymentsTotal property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPaymentsTotal() {
            return paymentsTotal;
        }

        /**
         * Sets the value of the paymentsTotal property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPaymentsTotal(BigDecimal value) {
            this.paymentsTotal = value;
        }

        /**
         * Gets the value of the paymentsCount property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getPaymentsCount() {
            return paymentsCount;
        }

        /**
         * Sets the value of the paymentsCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPaymentsCount(BigInteger value) {
            this.paymentsCount = value;
        }

        /**
         * Gets the value of the discountsTotal property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getDiscountsTotal() {
            return discountsTotal;
        }

        /**
         * Sets the value of the discountsTotal property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setDiscountsTotal(BigDecimal value) {
            this.discountsTotal = value;
        }

        /**
         * Gets the value of the discountsCount property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getDiscountsCount() {
            return discountsCount;
        }

        /**
         * Sets the value of the discountsCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setDiscountsCount(BigInteger value) {
            this.discountsCount = value;
        }

        /**
         * Gets the value of the giftcardSoldTotal property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getGiftcardSoldTotal() {
            return giftcardSoldTotal;
        }

        /**
         * Sets the value of the giftcardSoldTotal property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setGiftcardSoldTotal(BigDecimal value) {
            this.giftcardSoldTotal = value;
        }

        /**
         * Gets the value of the giftcardSoldCount property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getGiftcardSoldCount() {
            return giftcardSoldCount;
        }

        /**
         * Sets the value of the giftcardSoldCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setGiftcardSoldCount(BigInteger value) {
            this.giftcardSoldCount = value;
        }

        /**
         * Gets the value of the payments property.
         * 
         * @return
         *     possible object is
         *     {@link Sales.Summary.Payments }
         *     
         */
        public Sales.Summary.Payments getPayments() {
            return payments;
        }

        /**
         * Sets the value of the payments property.
         * 
         * @param value
         *     allowed object is
         *     {@link Sales.Summary.Payments }
         *     
         */
        public void setPayments(Sales.Summary.Payments value) {
            this.payments = value;
        }

        /**
         * Gets the value of the auxiliaries property.
         * 
         * @return
         *     possible object is
         *     {@link Sales.Summary.Auxiliaries }
         *     
         */
        public Sales.Summary.Auxiliaries getAuxiliaries() {
            return auxiliaries;
        }

        /**
         * Sets the value of the auxiliaries property.
         * 
         * @param value
         *     allowed object is
         *     {@link Sales.Summary.Auxiliaries }
         *     
         */
        public void setAuxiliaries(Sales.Summary.Auxiliaries value) {
            this.auxiliaries = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element name="auxiliary" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "auxiliary"
        })
        public static class Auxiliaries {

            protected List<Sales.Summary.Auxiliaries.Auxiliary> auxiliary;

            /**
             * Gets the value of the auxiliary property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the auxiliary property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAuxiliary().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Sales.Summary.Auxiliaries.Auxiliary }
             * 
             * 
             */
            public List<Sales.Summary.Auxiliaries.Auxiliary> getAuxiliary() {
                if (auxiliary == null) {
                    auxiliary = new ArrayList<Sales.Summary.Auxiliaries.Auxiliary>();
                }
                return this.auxiliary;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Auxiliary {

                @XmlValue
                protected String value;
                @XmlAttribute
                protected String name;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="payment" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;all>
         *                   &lt;element name="credit_total" type="{http://speedorder.speedfc.com/xml/types}numeric19s2"/>
         *                   &lt;element name="credit_count" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *                   &lt;element name="debit_total" type="{http://speedorder.speedfc.com/xml/types}numeric19s2"/>
         *                   &lt;element name="debit_count" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *                 &lt;/all>
         *                 &lt;attribute name="type" use="required" type="{http://speedorder.speedfc.com/xml/types}varchar10" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "payment"
        })
        public static class Payments {

            protected List<Sales.Summary.Payments.Payment> payment;

            /**
             * Gets the value of the payment property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the payment property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPayment().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Sales.Summary.Payments.Payment }
             * 
             * 
             */
            public List<Sales.Summary.Payments.Payment> getPayment() {
                if (payment == null) {
                    payment = new ArrayList<Sales.Summary.Payments.Payment>();
                }
                return this.payment;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;all>
             *         &lt;element name="credit_total" type="{http://speedorder.speedfc.com/xml/types}numeric19s2"/>
             *         &lt;element name="credit_count" type="{http://www.w3.org/2001/XMLSchema}integer"/>
             *         &lt;element name="debit_total" type="{http://speedorder.speedfc.com/xml/types}numeric19s2"/>
             *         &lt;element name="debit_count" type="{http://www.w3.org/2001/XMLSchema}integer"/>
             *       &lt;/all>
             *       &lt;attribute name="type" use="required" type="{http://speedorder.speedfc.com/xml/types}varchar10" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {

            })
            public static class Payment {

                @XmlElement(name = "credit_total", required = true)
                protected BigDecimal creditTotal;
                @XmlElement(name = "credit_count", required = true)
                protected BigInteger creditCount;
                @XmlElement(name = "debit_total", required = true)
                protected BigDecimal debitTotal;
                @XmlElement(name = "debit_count", required = true)
                protected BigInteger debitCount;
                @XmlAttribute(required = true)
                protected String type;

                /**
                 * Gets the value of the creditTotal property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getCreditTotal() {
                    return creditTotal;
                }

                /**
                 * Sets the value of the creditTotal property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setCreditTotal(BigDecimal value) {
                    this.creditTotal = value;
                }

                /**
                 * Gets the value of the creditCount property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getCreditCount() {
                    return creditCount;
                }

                /**
                 * Sets the value of the creditCount property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setCreditCount(BigInteger value) {
                    this.creditCount = value;
                }

                /**
                 * Gets the value of the debitTotal property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getDebitTotal() {
                    return debitTotal;
                }

                /**
                 * Sets the value of the debitTotal property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setDebitTotal(BigDecimal value) {
                    this.debitTotal = value;
                }

                /**
                 * Gets the value of the debitCount property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getDebitCount() {
                    return debitCount;
                }

                /**
                 * Sets the value of the debitCount property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setDebitCount(BigInteger value) {
                    this.debitCount = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }

            }

        }

    }

}
