//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.09 at 08:22:26 AM EST 
//


package oms.commerce.salesaudit.schema.type;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the oms.commerce.salesaudit.schema.type package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: oms.commerce.salesaudit.schema.type
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link LineDiscountType }
     * 
     */
    public LineDiscountType createLineDiscountType() {
        return new LineDiscountType();
    }

    /**
     * Create an instance of {@link OrderAppeasementType }
     * 
     */
    public OrderAppeasementType createOrderAppeasementType() {
        return new OrderAppeasementType();
    }

    /**
     * Create an instance of {@link CustomerType }
     * 
     */
    public CustomerType createCustomerType() {
        return new CustomerType();
    }

    /**
     * Create an instance of {@link Period }
     * 
     */
    public Period createPeriod() {
        return new Period();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link OrderPayment.Auxiliaries.Auxiliary }
     * 
     */
    public OrderPayment.Auxiliaries.Auxiliary createOrderPaymentAuxiliariesAuxiliary() {
        return new OrderPayment.Auxiliaries.Auxiliary();
    }

    /**
     * Create an instance of {@link ContactType }
     * 
     */
    public ContactType createContactType() {
        return new ContactType();
    }

    /**
     * Create an instance of {@link OrderPayment.Auxiliaries }
     * 
     */
    public OrderPayment.Auxiliaries createOrderPaymentAuxiliaries() {
        return new OrderPayment.Auxiliaries();
    }

    /**
     * Create an instance of {@link TaxAmount }
     * 
     */
    public TaxAmount createTaxAmount() {
        return new TaxAmount();
    }

    /**
     * Create an instance of {@link OrderPayment }
     * 
     */
    public OrderPayment createOrderPayment() {
        return new OrderPayment();
    }

    /**
     * Create an instance of {@link AddressLineType }
     * 
     */
    public AddressLineType createAddressLineType() {
        return new AddressLineType();
    }

}
