//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.09 at 08:22:26 AM EST 
//


package oms.commerce.salesaudit.schema.type;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TaxAmount complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaxAmount">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="local" type="{http://speedorder.speedfc.com/xml/types}numeric19s4"/>
 *         &lt;element name="county" type="{http://speedorder.speedfc.com/xml/types}numeric19s4"/>
 *         &lt;element name="state" type="{http://speedorder.speedfc.com/xml/types}numeric19s4"/>
 *         &lt;element name="total" type="{http://speedorder.speedfc.com/xml/types}numeric19s4"/>
 *         &lt;element name="shipping_tax" type="{http://speedorder.speedfc.com/xml/types}numeric19s4" minOccurs="0"/>
 *         &lt;element name="extended_total" type="{http://speedorder.speedfc.com/xml/types}numeric19s4"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaxAmount", propOrder = {
    "local",
    "county",
    "state",
    "total",
    "shippingTax",
    "extendedTotal"
})
public class TaxAmount {

    @XmlElement(required = true)
    protected BigDecimal local;
    @XmlElement(required = true)
    protected BigDecimal county;
    @XmlElement(required = true)
    protected BigDecimal state;
    @XmlElement(required = true)
    protected BigDecimal total;
    @XmlElement(name = "shipping_tax")
    protected BigDecimal shippingTax;
    @XmlElement(name = "extended_total", required = true)
    protected BigDecimal extendedTotal;

    /**
     * Gets the value of the local property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLocal() {
        return local;
    }

    /**
     * Sets the value of the local property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLocal(BigDecimal value) {
        this.local = value;
    }

    /**
     * Gets the value of the county property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCounty() {
        return county;
    }

    /**
     * Sets the value of the county property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCounty(BigDecimal value) {
        this.county = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setState(BigDecimal value) {
        this.state = value;
    }

    /**
     * Gets the value of the total property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotal(BigDecimal value) {
        this.total = value;
    }

    /**
     * Gets the value of the shippingTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getShippingTax() {
        return shippingTax;
    }

    /**
     * Sets the value of the shippingTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setShippingTax(BigDecimal value) {
        this.shippingTax = value;
    }

    /**
     * Gets the value of the extendedTotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExtendedTotal() {
        return extendedTotal;
    }

    /**
     * Sets the value of the extendedTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExtendedTotal(BigDecimal value) {
        this.extendedTotal = value;
    }

}
